package dao;

import entity.Exchange;
import entity.ExchangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int countByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int deleteByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int deleteByPrimaryKey(Integer exchangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int insert(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int insertSelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    List<Exchange> selectByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    Exchange selectByPrimaryKey(Integer exchangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exchange record, @Param("example") ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int updateByExample(@Param("record") Exchange record, @Param("example") ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int updateByPrimaryKeySelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    int updateByPrimaryKey(Exchange record);
}