package dao;

import entity.Sell;
import entity.SellExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int countByExample(SellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int deleteByExample(SellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int insert(Sell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int insertSelective(Sell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    List<Sell> selectByExample(SellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    Sell selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sell record, @Param("example") SellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int updateByExample(@Param("record") Sell record, @Param("example") SellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int updateByPrimaryKeySelective(Sell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    int updateByPrimaryKey(Sell record);
}