package entity;

public class Exchange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.exchangeid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    private Integer exchangeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.ohteritemid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    private Integer ohteritemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.myitemid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    private Integer myitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange.exchangeerid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    private Long exchangeerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.exchangeid
     *
     * @return the value of exchange.exchangeid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public Integer getExchangeid() {
        return exchangeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.exchangeid
     *
     * @param exchangeid the value for exchange.exchangeid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void setExchangeid(Integer exchangeid) {
        this.exchangeid = exchangeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.ohteritemid
     *
     * @return the value of exchange.ohteritemid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public Integer getOhteritemid() {
        return ohteritemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.ohteritemid
     *
     * @param ohteritemid the value for exchange.ohteritemid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void setOhteritemid(Integer ohteritemid) {
        this.ohteritemid = ohteritemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.myitemid
     *
     * @return the value of exchange.myitemid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public Integer getMyitemid() {
        return myitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.myitemid
     *
     * @param myitemid the value for exchange.myitemid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void setMyitemid(Integer myitemid) {
        this.myitemid = myitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange.exchangeerid
     *
     * @return the value of exchange.exchangeerid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public Long getExchangeerid() {
        return exchangeerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange.exchangeerid
     *
     * @param exchangeerid the value for exchange.exchangeerid
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void setExchangeerid(Long exchangeerid) {
        this.exchangeerid = exchangeerid;
    }
}