package entity;

import java.util.ArrayList;
import java.util.List;

public class ExchangeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public ExchangeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExchangeidIsNull() {
            addCriterion("exchangeid is null");
            return (Criteria) this;
        }

        public Criteria andExchangeidIsNotNull() {
            addCriterion("exchangeid is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeidEqualTo(Integer value) {
            addCriterion("exchangeid =", value, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidNotEqualTo(Integer value) {
            addCriterion("exchangeid <>", value, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidGreaterThan(Integer value) {
            addCriterion("exchangeid >", value, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("exchangeid >=", value, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidLessThan(Integer value) {
            addCriterion("exchangeid <", value, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidLessThanOrEqualTo(Integer value) {
            addCriterion("exchangeid <=", value, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidIn(List<Integer> values) {
            addCriterion("exchangeid in", values, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidNotIn(List<Integer> values) {
            addCriterion("exchangeid not in", values, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidBetween(Integer value1, Integer value2) {
            addCriterion("exchangeid between", value1, value2, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andExchangeidNotBetween(Integer value1, Integer value2) {
            addCriterion("exchangeid not between", value1, value2, "exchangeid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidIsNull() {
            addCriterion("ohteritemid is null");
            return (Criteria) this;
        }

        public Criteria andOhteritemidIsNotNull() {
            addCriterion("ohteritemid is not null");
            return (Criteria) this;
        }

        public Criteria andOhteritemidEqualTo(Integer value) {
            addCriterion("ohteritemid =", value, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidNotEqualTo(Integer value) {
            addCriterion("ohteritemid <>", value, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidGreaterThan(Integer value) {
            addCriterion("ohteritemid >", value, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ohteritemid >=", value, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidLessThan(Integer value) {
            addCriterion("ohteritemid <", value, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidLessThanOrEqualTo(Integer value) {
            addCriterion("ohteritemid <=", value, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidIn(List<Integer> values) {
            addCriterion("ohteritemid in", values, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidNotIn(List<Integer> values) {
            addCriterion("ohteritemid not in", values, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidBetween(Integer value1, Integer value2) {
            addCriterion("ohteritemid between", value1, value2, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andOhteritemidNotBetween(Integer value1, Integer value2) {
            addCriterion("ohteritemid not between", value1, value2, "ohteritemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidIsNull() {
            addCriterion("myitemid is null");
            return (Criteria) this;
        }

        public Criteria andMyitemidIsNotNull() {
            addCriterion("myitemid is not null");
            return (Criteria) this;
        }

        public Criteria andMyitemidEqualTo(Integer value) {
            addCriterion("myitemid =", value, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidNotEqualTo(Integer value) {
            addCriterion("myitemid <>", value, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidGreaterThan(Integer value) {
            addCriterion("myitemid >", value, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("myitemid >=", value, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidLessThan(Integer value) {
            addCriterion("myitemid <", value, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidLessThanOrEqualTo(Integer value) {
            addCriterion("myitemid <=", value, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidIn(List<Integer> values) {
            addCriterion("myitemid in", values, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidNotIn(List<Integer> values) {
            addCriterion("myitemid not in", values, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidBetween(Integer value1, Integer value2) {
            addCriterion("myitemid between", value1, value2, "myitemid");
            return (Criteria) this;
        }

        public Criteria andMyitemidNotBetween(Integer value1, Integer value2) {
            addCriterion("myitemid not between", value1, value2, "myitemid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridIsNull() {
            addCriterion("exchangeerid is null");
            return (Criteria) this;
        }

        public Criteria andExchangeeridIsNotNull() {
            addCriterion("exchangeerid is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeeridEqualTo(Long value) {
            addCriterion("exchangeerid =", value, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridNotEqualTo(Long value) {
            addCriterion("exchangeerid <>", value, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridGreaterThan(Long value) {
            addCriterion("exchangeerid >", value, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridGreaterThanOrEqualTo(Long value) {
            addCriterion("exchangeerid >=", value, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridLessThan(Long value) {
            addCriterion("exchangeerid <", value, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridLessThanOrEqualTo(Long value) {
            addCriterion("exchangeerid <=", value, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridIn(List<Long> values) {
            addCriterion("exchangeerid in", values, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridNotIn(List<Long> values) {
            addCriterion("exchangeerid not in", values, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridBetween(Long value1, Long value2) {
            addCriterion("exchangeerid between", value1, value2, "exchangeerid");
            return (Criteria) this;
        }

        public Criteria andExchangeeridNotBetween(Long value1, Long value2) {
            addCriterion("exchangeerid not between", value1, value2, "exchangeerid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exchange
     *
     * @mbggenerated do_not_delete_during_merge Wed May 30 00:41:58 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exchange
     *
     * @mbggenerated Wed May 30 00:41:58 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}