package entity;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.buyerid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private Long buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.sellerid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private Long sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.status
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.bookname
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.author
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.press
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.kind
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.version
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.qq
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.phone
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.address
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.images
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.other
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemid
     *
     * @return the value of item.itemid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemid
     *
     * @param itemid the value for item.itemid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.buyerid
     *
     * @return the value of item.buyerid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public Long getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.buyerid
     *
     * @param buyerid the value for item.buyerid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setBuyerid(Long buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sellerid
     *
     * @return the value of item.sellerid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public Long getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sellerid
     *
     * @param sellerid the value for item.sellerid
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setSellerid(Long sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.status
     *
     * @return the value of item.status
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.status
     *
     * @param status the value for item.status
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.bookname
     *
     * @return the value of item.bookname
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.bookname
     *
     * @param bookname the value for item.bookname
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.author
     *
     * @return the value of item.author
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.author
     *
     * @param author the value for item.author
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.press
     *
     * @return the value of item.press
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.press
     *
     * @param press the value for item.press
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.kind
     *
     * @return the value of item.kind
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.kind
     *
     * @param kind the value for item.kind
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.version
     *
     * @return the value of item.version
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.version
     *
     * @param version the value for item.version
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.qq
     *
     * @return the value of item.qq
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.qq
     *
     * @param qq the value for item.qq
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.phone
     *
     * @return the value of item.phone
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.phone
     *
     * @param phone the value for item.phone
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.address
     *
     * @return the value of item.address
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.address
     *
     * @param address the value for item.address
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.images
     *
     * @return the value of item.images
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.images
     *
     * @param images the value for item.images
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.other
     *
     * @return the value of item.other
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.other
     *
     * @param other the value for item.other
     *
     * @mbggenerated Sun Jun 03 16:33:19 CST 2018
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}