package entity;

public class Sell {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell.id
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell.userid
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell.issellok
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    private Integer issellok;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell.itemid
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    private Integer itemid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell.id
     *
     * @return the value of sell.id
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell.id
     *
     * @param id the value for sell.id
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell.userid
     *
     * @return the value of sell.userid
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell.userid
     *
     * @param userid the value for sell.userid
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell.issellok
     *
     * @return the value of sell.issellok
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public Integer getIssellok() {
        return issellok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell.issellok
     *
     * @param issellok the value for sell.issellok
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public void setIssellok(Integer issellok) {
        this.issellok = issellok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell.itemid
     *
     * @return the value of sell.itemid
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell.itemid
     *
     * @param itemid the value for sell.itemid
     *
     * @mbggenerated Sat Jun 09 19:24:53 CST 2018
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }
}